sudo: true
language: node_js
compiler: g++
node_js:
  - '0.5.1'
  - '0.4.2'
  - 'iojs'

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-5.3
  - export CXX="g++-5.3"

script: npm test 
