environment:
  matrix:
    - nodejs_version: "5"
    - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm install -g npm@next
  - npm --version
  - npm install -g gulp
  - npm install -g standard
  - npm install

test_script:
  - gulp appveyor_test

build: off
